services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle-db
    cap_add:
      - SYS_NICE
      - SYS_TIME
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle-pwd
      APP_USER: app
      APP_USER_PASSWORD: app
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    volumes:
      - ./OracleDb/data:/opt/oracle/oradata
      - ./OracleDb/logs:/opt/oracle/diag

  webapp:
    build:
      context: ./ServerIIS
      dockerfile: Dockerfile
    container_name: webapp
    depends_on:
      oracle-db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "dotnet", "--info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
